language: haskell
ghc: 7.8
sudo: required

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
    - $HOME/.local/bin
    - $HOME/pandoc/.stack

install:
  - mkdir -p ~/rust-installer ~/rust
  - curl -sL https://static.rust-lang.org/rustup.sh -o ~/rust-installer/rustup.sh
  - sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=stable -y --disable-sudo 2> /dev/null
  - export PATH=$PATH:$HOME/rust/bin
  # pandoc with fixed https://github.com/jgm/pandoc/issues/3277
  - |
    if [[ ! -a ~/.local/bin/pandoc ]] || [[ ! -d ~/pandoc ]]
    then
        echo 'deb http://download.fpcomplete.com/ubuntu precise main' \
            | sudo tee /etc/apt/sources.list.d/fpco.list
        sudo apt-get update
        sudo apt-get install stack -y --force-yes
        git clone \
            --depth 1 \
            --recursive \
            https://github.com/jgm/pandoc.git ~/pandoc
        ( cd ~/pandoc \
            && stack setup \
            && stack install --test )
    fi
    export PATH=$PATH:$HOME/.local/bin

script:
  - make
  - make format
  # Check that make format was executed before submitting.
  - git diff --exit-code

branches:
  only:
    - master

after_success:
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] \
        && [[ "$TRAVIS_BRANCH" == "master" ]]
    then
        mkdir www
        cp rust.css www/
        cp spec.html www/index.html
        cp -r img www/
        ./deploy-gh-pages.sh
    fi
