language: rust
rust: stable

script:
  - make spec.html
  - test -f spec.html

branches:
  only:
    - master

after_success:
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] \
        && [[ "$TRAVIS_BRANCH" == "master" ]]
    then
        mkdir www
        cp rust.css www/
        cp spec.html www/index.html
        cp -r img www/
        ./deploy-gh-pages.sh
    fi
